spring:
  jwt:
    secret: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e440293f765eae731f5a65ed1"

admin:
  username: admin
  password: admin1234
  nickname: ???

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /doc
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
